"""The last of the German field labels, translated.

State only: `verbose_name` lives in the migration graph but never in the
database, so this issues no SQL. It exists so `makemigrations --check` stays
quiet -- and it lands now because the profile form is the first screen to put
these labels in front of anyone. `0002_english_labels` carried two of them
forward untranslated; this is where they catch up.
"""

# Generated by Django 5.2.17 on 2026-09-07 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_english_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate instead of deleting to lock an account out.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Whether this person may sign in to the admin site.', verbose_name='Team member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_invited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last invited'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last name'),
        ),
    ]
