# Generated by Django 5.2.17 on 2026-09-06 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=4, unique=True, verbose_name='Kürzel')),
                ('conference', models.CharField(blank=True, choices=[('EAST', 'Eastern Conference'), ('WEST', 'Western Conference')], max_length=4, verbose_name='Conference')),
                ('division', models.CharField(blank=True, choices=[('ATLANTIC', 'Atlantic'), ('CENTRAL', 'Central'), ('SOUTHEAST', 'Southeast'), ('NORTHWEST', 'Northwest'), ('PACIFIC', 'Pacific'), ('SOUTHWEST', 'Southwest')], max_length=16, verbose_name='Division')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=64, verbose_name='Nachname')),
                ('position', models.CharField(choices=[('G', 'Guard'), ('F', 'Forward'), ('C', 'Center')], max_length=1, verbose_name='Position')),
                ('is_active', models.BooleanField(default=True, help_text='Cleared by the import when a player stops appearing in the source.', verbose_name='Aktiv')),
                ('team', models.ForeignKey(blank=True, help_text='Empty for free agents or players not currently on a roster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='nba.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Spieler',
                'verbose_name_plural': 'Spieler',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='nba_player_last_na_77e495_idx'), models.Index(fields=['position'], name='nba_player_positio_a45b8a_idx')],
            },
        ),
    ]
