# Generated by Django 5.2.17 on 2026-09-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aus dem jüngsten Spielerstand übernommen. Leer, solange keiner vorliegt.', max_digits=12, null=True, verbose_name='Aktuelles Gehalt'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['current_salary'], name='nba_player_current_e06427_idx'),
        ),
    ]
