# Generated by Django 5.2.17 on 2026-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_player_current_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_fp_per_game',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leer, solange kein Spiel absolviert wurde.', max_digits=8, null=True, verbose_name='Punkte pro Spiel'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_games_played',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Absolvierte Spiele, aus dem jüngsten Spielerstand.', null=True, verbose_name='Spiele'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_total_fp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punkte der laufenden Saison, aus dem jüngsten Spielerstand.', max_digits=8, null=True, verbose_name='Fantasy-Punkte'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['current_fp_per_game'], name='nba_player_current_6bc54a_idx'),
        ),
    ]
