# Generated by Django 5.2.17 on 2026-09-12 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0004_english_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInjury',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='api-basketball-nba', max_length=64, verbose_name='Provider')),
                ('provider_injury_id', models.CharField(blank=True, max_length=64, verbose_name='Provider injury ID')),
                ('observed_at', models.DateTimeField(verbose_name='Observed at')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Reported at')),
                ('status', models.CharField(max_length=64, verbose_name='Status')),
                ('fantasy_status', models.CharField(blank=True, max_length=64, verbose_name='Fantasy status')),
                ('fantasy_status_abbreviation', models.CharField(blank=True, max_length=16, verbose_name='Fantasy status abbreviation')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Expected return date')),
                ('injury_type', models.CharField(blank=True, max_length=128, verbose_name='Injury type')),
                ('injury_location', models.CharField(blank=True, max_length=128, verbose_name='Injury location')),
                ('injury_detail', models.CharField(blank=True, max_length=128, verbose_name='Injury detail')),
                ('injury_side', models.CharField(blank=True, max_length=64, verbose_name='Injury side')),
                ('short_comment', models.TextField(blank=True, verbose_name='Short comment')),
                ('long_comment', models.TextField(blank=True, verbose_name='Long comment')),
                ('headline', models.TextField(blank=True, verbose_name='Headline')),
                ('headline_source', models.CharField(blank=True, max_length=128, verbose_name='Headline source')),
                ('feed_player_name', models.CharField(blank=True, max_length=160, verbose_name='Feed player name')),
                ('feed_team_id', models.CharField(blank=True, max_length=64, verbose_name='Feed team ID')),
                ('feed_team_abbreviation', models.CharField(blank=True, max_length=8, verbose_name='Feed team abbreviation')),
                ('feed_team_name', models.CharField(blank=True, max_length=128, verbose_name='Feed team name')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw provider payload')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='nba.player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player injury',
                'verbose_name_plural': 'Player injuries',
                'ordering': ['-observed_at', '-created_at'],
                'indexes': [models.Index(fields=['player', '-observed_at'], name='nba_playeri_player__d14272_idx'), models.Index(fields=['status'], name='nba_playeri_status_73cd6b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_injury_id', ''), _negated=True), fields=('provider', 'provider_injury_id'), name='unique_provider_injury_id')],
            },
        ),
    ]
