# Generated by Django 5.2.17 on 2026-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0005_playerinjury'),
    ]

    operations = [
        migrations.CreateModel(
            name='NbaApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=64, verbose_name='Provider')),
                ('usage_date', models.DateField(verbose_name='Usage date')),
                ('request_count', models.PositiveSmallIntegerField(default=0, verbose_name='Request count')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'usage_date'), name='one_api_usage_row_per_day')],
            },
        ),
    ]
