# Generated by Django 5.2.17 on 2026-09-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0006_nbaapiusage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerinjury',
            name='unique_provider_injury_id',
        ),
        migrations.AddConstraint(
            model_name='playerinjury',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_injury_id', ''), _negated=True), fields=('provider', 'provider_injury_id', 'observed_at'), name='unique_provider_injury_observation'),
        ),
    ]
