# Generated by Django 5.2.17 on 2026-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0007_remove_playerinjury_unique_provider_injury_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinjury',
            name='feed_athlete_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Feed athlete ID'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='feed_player_position',
            field=models.CharField(blank=True, max_length=64, verbose_name='Feed player position'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='feed_player_position_abbreviation',
            field=models.CharField(blank=True, max_length=8, verbose_name='Feed player position abbreviation'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='feed_player_status',
            field=models.CharField(blank=True, max_length=64, verbose_name='Feed player status'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='injury_status_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Injury status type'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='provider_source_description',
            field=models.CharField(blank=True, max_length=128, verbose_name='Provider source description'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='provider_source_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Provider source ID'),
        ),
        migrations.AddField(
            model_name='playerinjury',
            name='provider_source_state',
            field=models.CharField(blank=True, max_length=32, verbose_name='Provider source state'),
        ),
    ]
