# Generated by Django 5.2.17 on 2026-09-14 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0008_playerinjury_feed_athlete_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Note')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='nba.player', verbose_name='Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_notes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Player note',
                'verbose_name_plural': 'Player notes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'player'), name='one_note_per_user_per_player')],
            },
        ),
    ]
