# Generated by Django 5.2.17 on 2026-09-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0009_playernote'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playernote',
            name='one_note_per_user_per_player',
        ),
    ]
