# Generated by Django 5.2.17 on 2026-10-03 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_remove_transaction_a_transaction_moves_at_least_one_player_and_more'),
        ('nba', '0011_teamnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bbde_id',
            field=models.PositiveIntegerField(blank=True, help_text='Set by the import. Fill in by hand to link a player the import could not match.', null=True, unique=True, verbose_name='basketball.de ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_rookie',
            field=models.BooleanField(default=False, help_text='As flagged by the official game. Set by the import.', verbose_name='Rookie'),
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('source', models.CharField(choices=[('web', 'Web'), ('command', 'Command')], max_length=16, verbose_name='Source')),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='Status')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry run')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Pages')),
                ('rows', models.PositiveIntegerField(default=0, verbose_name='Rows')),
                ('matched', models.PositiveIntegerField(default=0, verbose_name='Matched')),
                ('created', models.PositiveIntegerField(default=0, verbose_name='Created')),
                ('reactivated', models.PositiveIntegerField(default=0, verbose_name='Reactivated')),
                ('inactivated', models.PositiveIntegerField(default=0, verbose_name='Inactivated')),
                ('created_players', models.JSONField(blank=True, default=list, verbose_name='Created players')),
                ('ambiguous', models.JSONField(blank=True, default=list, verbose_name='Ambiguous rows')),
                ('skipped', models.JSONField(blank=True, default=list, verbose_name='Skipped rows')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Warnings')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasy.season', verbose_name='Season')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Triggered by')),
            ],
            options={
                'verbose_name': 'Import run',
                'verbose_name_plural': 'Import runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
