# Generated by Django 5.2.17 on 2026-09-06 19:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nba', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=16, unique=True, verbose_name='Bezeichnung')),
                ('starts_on', models.DateField(verbose_name='Beginn')),
                ('ends_on', models.DateField(verbose_name='Ende')),
                ('is_current', models.BooleanField(default=False, verbose_name='Aktuell')),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['-starts_on'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_season'), models.CheckConstraint(condition=models.Q(('ends_on__gt', models.F('starts_on'))), name='season_ends_after_it_starts')],
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('60000000'), max_digits=12, verbose_name='Guthaben')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer:in')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters', to='fantasy.season', verbose_name='Saison')),
            ],
            options={
                'verbose_name': 'Kader',
                'verbose_name_plural': 'Kader',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('cash_delta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Geldfluss')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('player_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_in', to='nba.player', verbose_name='Zugang')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_out', to='nba.player', verbose_name='Abgang')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fantasy.roster', verbose_name='Kader')),
            ],
            options={
                'verbose_name': 'Transaktion',
                'verbose_name_plural': 'Transaktionen',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_at', models.DateTimeField(verbose_name='Aufgenommen')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgegeben')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_memberships', to='nba.player', verbose_name='Spieler')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fantasy.roster', verbose_name='Kader')),
            ],
            options={
                'verbose_name': 'Kaderzugehörigkeit',
                'verbose_name_plural': 'Kaderzugehörigkeiten',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('roster', 'player'), name='a_player_is_on_a_roster_once_at_a_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.UniqueConstraint(fields=('owner', 'season', 'name'), name='unique_roster_name_per_season'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.CheckConstraint(condition=models.Q(('cash__gte', 0)), name='cash_is_never_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('player_in__isnull', False), ('player_out__isnull', False), _connector='OR'), name='a_transaction_moves_at_least_one_player'),
        ),
    ]
