# Generated by Django 5.2.17 on 2026-09-07 05:53

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField(verbose_name='Stand')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gehalt')),
                ('total_fp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fantasy-Punkte')),
                ('games_played', models.PositiveSmallIntegerField(verbose_name='Spiele')),
                ('fp_per_game', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('total_fp'), '/', django.db.models.functions.comparison.NullIf(models.F('games_played'), 0)), output_field=models.DecimalField(decimal_places=2, max_digits=8), verbose_name='Punkte pro Spiel')),
                ('position', models.CharField(choices=[('G', 'Guard'), ('F', 'Forward'), ('C', 'Center')], max_length=1, verbose_name='Position')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='nba.player', verbose_name='Spieler')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='fantasy.season', verbose_name='Saison')),
                ('team', models.ForeignKey(blank=True, help_text='Das Team, das die Quelle zu diesem Zeitpunkt gemeldet hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_snapshots', to='nba.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Spielerstand',
                'verbose_name_plural': 'Spielerstände',
                'ordering': ['-as_of', 'player'],
                'indexes': [models.Index(fields=['player', '-as_of'], name='fantasy_pla_player__fb1a80_idx'), models.Index(fields=['season', '-as_of'], name='fantasy_pla_season__d4e488_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'season', 'as_of'), name='one_snapshot_per_player_and_moment')],
            },
        ),
    ]
