# Generated by Django 5.2.17 on 2026-09-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_expand_roster_icons'),
        ('nba', '0008_playerinjury_feed_athlete_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='a_transaction_moves_at_least_one_player',
        ),
        migrations.AddField(
            model_name='roster',
            name='trades_available',
            field=models.PositiveIntegerField(default=2, verbose_name='Available trades'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('TRADE', 'Trade'), ('BUY_TRADE', 'Buy Trade'), ('SELL_TRADE', 'Sell Trade')], max_length=20, verbose_name='Kind'),
        ),
        migrations.AddConstraint(
            model_name='roster',
            constraint=models.CheckConstraint(condition=models.Q(('trades_available__gte', 0)), name='trades_available_is_never_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('player_in__isnull', False), ('player_out__isnull', False), ('kind__in', ['BUY_TRADE', 'SELL_TRADE']), _connector='OR'), name='a_transaction_moves_at_least_one_player_or_trade'),
        ),
    ]
