# Generated by Django 5.2.17 on 2026-10-03 19:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_remove_transaction_a_transaction_moves_at_least_one_player_and_more'),
        ('nba', '0012_bbde_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(verbose_name='Granted at')),
                ('trades', models.PositiveSmallIntegerField(default=1, verbose_name='Trades')),
                ('label', models.CharField(max_length=80, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Trade grant',
                'verbose_name_plural': 'Trade grants',
                'ordering': ['granted_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='a_transaction_moves_at_least_one_player_or_trade',
        ),
        # Rosters that exist already were all created under the old fixed
        # budget of $60M, so that is their starting budget.
        migrations.AddField(
            model_name='roster',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('60000000'), max_digits=12, verbose_name='Starting budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('63000000'), help_text='What every new roster of this season starts with, in dollars.', max_digits=12, verbose_name='Starting budget'),
        ),
        migrations.AddField(
            model_name='season',
            name='trade_market_closes_at',
            field=models.DateTimeField(blank=True, help_text='After this moment trades can no longer be bought or sold. Leave empty for no limit.', null=True, verbose_name='Trade buying closes'),
        ),
        migrations.AddField(
            model_name='season',
            name='trade_market_opens_at',
            field=models.DateTimeField(blank=True, help_text='From this moment trades can be bought and sold. Leave empty for no limit.', null=True, verbose_name='Trade buying opens'),
        ),
        migrations.AddField(
            model_name='season',
            name='weekly_trades_from',
            field=models.DateTimeField(blank=True, help_text='The first weekly trade. Another follows every 7 days at the same time until the season ends. Leave empty for no weekly trades.', null=True, verbose_name='Weekly trades from'),
        ),
        migrations.AddField(
            model_name='season',
            name='weekly_trades_per_week',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many trades each weekly grant adds to every roster.', verbose_name='Trades per week'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='grant_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Grant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trades_granted',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trades granted'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cash'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='trades_available',
            field=models.PositiveIntegerField(default=0, verbose_name='Available trades'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('TRADE', 'Trade'), ('BUY_TRADE', 'Buy Trade'), ('SELL_TRADE', 'Sell Trade'), ('GRANT_TRADE', 'Trade granted')], max_length=20, verbose_name='Kind'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('starting_cash__gte', 0)), name='season_starting_cash_is_never_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('player_in__isnull', False), ('player_out__isnull', False), ('kind__in', ['BUY_TRADE', 'SELL_TRADE', 'GRANT_TRADE']), _connector='OR'), name='a_transaction_moves_at_least_one_player_or_trade'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('grant_key', ''), _negated=True), fields=('roster', 'grant_key'), name='a_trade_grant_is_paid_once_per_roster'),
        ),
        migrations.AddField(
            model_name='tradegrant',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_grants', to='fantasy.season', verbose_name='Season'),
        ),
        migrations.AddConstraint(
            model_name='tradegrant',
            constraint=models.CheckConstraint(condition=models.Q(('trades__gte', 1)), name='a_trade_grant_grants_trades'),
        ),
    ]
